config/routes.rb
Rails.application.routes.draw do

  devise_for :"etabliocms_core/users", :path => ""

  match "/admin", :to => "etabliocms_core/admin/static#index"
  match "/admin/textile_parser", :to => "etabliocms_core/admin/static#textile_parser", :as => "textile_parser"
  match "/admin/textile_help", :to => "etabliocms_core/admin/static#textile_help", :as => "admin_textile_help"

  scope :module => "etabliocms_core" do
    namespace :admin do
      resources :users
    end
  end

end

app/models/etabliocms_core/user.rb
module EtabliocmsCore
  class User < ActiveRecord::Base

    devise :database_authenticatable, :recoverable, :rememberable, :validatable, :trackable

    attr_accessible :email, :password, :password_confirmation, :remember_me

    has_paper_trail

  end
end

app/controllers/etabliocms_core/admin/users_controller.rb
module EtabliocmsCore
  module Admin
    class UsersController < BaseController

      def index
        @users = User.all
      end

      def new
        @user = User.new
      end

      def create
        @user = User.new(params[:etabliocms_core_user])
        if @user.save
          flash[:notice] = t('etabliocms_core_user.created')
          redirect_to :action => 'index'
        else
          render :action => 'new'
        end
      end

      def edit
        @user = User.find(params[:id])
      end

      def update
        @user = User.find(params[:id])
        if params[:etabliocms_core_user][:password].blank? and params[:etabliocms_core_user][:password_confirmation].blank?
          params[:etabliocms_core_user].delete(:password)
          params[:etabliocms_core_user].delete(:password_confirmation)
        end
        if @user.update_attributes(params[:etabliocms_core_user])
          flash[:notice] = t('etabliocms_core_user.updated')
          redirect_to :action => 'index'
        else
          render :action => 'edit'
        end
      end

      def destroy
        User.find(params[:id]).destroy
        flash[:notice] = t('etabliocms_core_user.destroyed')
        redirect_to :action => 'index'
      end

    end
  end
end

app/views/etabliocms_core/admin/users/_form.html.erb
<%= render "layouts/errors", :target => @user %>

<fieldset>
  <legend><%= t('etabliocms_core_user.admin_legend') %></legend>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email, :class => 'text-field' %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'text-field' %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => 'text-field' %>
  </p>

  <p class="submit-box">
    <%= submit_tag t('admin.save'), :class => 'submit' %>
  </p>

</fieldset>

app/views/etabliocms_core/admin/users/edit.html.erb
<% set_title_and_breadcrumb t('etabliocms_core_user.edit', :title => @user.email) %>

<h1><%= @user.email %></h1>

<%= form_for @user,  :url => admin_user_path(@user.id), :html => {:method => :put, :id => "admin-form"} do |f| -%>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end  %>

app/views/etabliocms_core/admin/users/index.html.erb
<% set_title_and_breadcrumb t('etabliocms_core_user.users') %>

<h1><%= t('etabliocms_core_user.users') %></h1>

<div class="strap">
  <%= link_to "#{t('etabliocms_core_user.add')} &raquo;".html_safe, new_admin_user_path, :class => 'text-icon icon-add' %>
  <%= link_to "#{t('admin.refresh')} &raquo;".html_safe, admin_users_path, :class => 'text-icon icon-refresh' %>
  <%= link_to "#{t('admin.back_to_admin')} &raquo;".html_safe, admin_path, :class => 'text-icon icon-backward' %>
</div>

<table class="admin-table">
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.etabliocms_core_user.email') %></th>
    <th><%= t('activerecord.attributes.etabliocms_core_user.last_sign_in_at') %></th>
    <th><%= t('admin.actions') %></th>
  </tr>
  </thead>
  <tbody>

  <% for item in @users %>
      <tr class="<%= cycle("odd-row", "even-row") -%>">
        <td><%= link_to item.email, edit_admin_user_url(item.id) %></td>
        <td><%= l(item.last_sign_in_at, :format => :short) if item.last_sign_in_at.is_a?(DateTime) %></td>
        <td>
          <%= link_to t('admin.edit'), edit_admin_user_url(item.id), :class => 'icon icon-edit', :title => t('admin.edit') %>
          <%= link_to t('admin.destroy'), admin_user_url(item.id),
                      :method => :delete,
                      :confirm => t('etabliocms_core_user.destroy_confirmation'),
                      :class => 'icon icon-destroy',
                      :title => t('admin.destroy') %>
        </td>
  <% end %>
  </tbody>
</table>

app/views/etabliocms_core/admin/users/new.html.erb
<% set_title_and_breadcrumb t('etabliocms_core_user.new') %>

<h1><%= t('etabliocms_core_user.new') %></h1>

<%= form_for @user,  :url => admin_users_url, :html => {:method => :post, :id => "admin-form"} do |f| -%>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end  %>