config/routes.rb
Rails.application.routes.draw do

  devise_for :"etabliocms_core/users", :path => ""

  match "/admin", :to => "etabliocms_core/admin/static#index"
  match "/admin/textile_parser", :to => "etabliocms_core/admin/static#textile_parser", :as => "textile_parser"
  match "/admin/textile_help", :to => "etabliocms_core/admin/static#textile_help", :as => "admin_textile_help"

  scope :module => "etabliocms_core" do
    namespace :admin do
      resources :users
    end
  end

end

app/views/layouts/_errors.html.erb
<% if target.errors.any? %>
    <div id="errorExplanation">
      <h2><%= t('common.error_explanation') %></h2>
      <ul>
        <% target.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_flashes.html.erb
<div id="flash">
  <%- flash.each do |name, msg| -%>
      <%- if msg.is_a?(String) %>
          <p class="<%= name %>">
            <a href="" class="flash-close" title="Zavřít">
              <img src="<%= asset_path "admin/icon-close.png" %>" alt="<%= t('common.close') %>"/></a>
            <%= msg %>
          </p>
      <%- end %>
  <%- end -%>
</div>

app/views/layouts/_footer.html.erb
<footer id="contact">
  <div id="contact-inner">
    <div id="contact-inner-inner">
      <div id="map">
        <div id="map-inner">
        </div>
      </div>
      <p><%= t('contact.name') %></p>
      <p><%= t('contact.street') %></p>
      <p><%= t('contact.city') %></p>
      <p></p>
      <table>
        <tr>
          <th><%= t('contact.phone') %>:</th>
          <td><%= t('contact.phone1') %>, <br/><%= t('contact.phone2') %></td>
        </tr>
        <tr>
          <th><%= t('contact.email') %>:</th>
          <td><a href="mailto:<%= configatron.email %>"><%= configatron.email %></a></td>
        </tr>
        <tr>
          <th><%= t('contact.opened') %>:</th>
          <td><%= t('contact.opening_time') %></td>
        </tr>
      </table>
      <%= link_to t('contact.facebook'), configatron.facebook, :id => "fb-link" %>

      <h3 class="centered"><%= t('contact.internet_prices') %></h3>

      <p class="centered grey"><%= t('contact.internet_prices_text') %></p>
    </div>
  </div>
</footer>

<footer id="conclusion">
  <p>
    <%= Date.today.year %> &copy; <%= link_to configatron.title, root_url %> | <%= link_to t('common.login'), new_user_session_path %>
  </p>
</footer>

app/views/layouts/_sidebar_core.html.erb
<h3><%= image_tag asset_path("admin/sidebar-users.png"), :alt => t('etabliocms_core_user.users') %><%= t('etabliocms_core_user.users') %></h3>
<ul>
  <li><%= link_to_unless_current I18n.t('etabliocms_core_user.users_count', :count => EtabliocmsCore::User.count), admin_users_path %></li>
  <li><%= link_to_unless_current t('etabliocms_core_user.add'), new_admin_user_path %></li>
</ul>

app/views/layouts/admin.html.erb
<!doctype html>
<!--[if lt IE 7 ]>
<html class="ie ie6" lang="cs"> <![endif]-->
<!--[if IE 7 ]>
<html class="ie ie7" lang="cs"> <![endif]-->
<!--[if IE 8 ]>
<html class="ie ie8" lang="cs"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="cs"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Language" content="cs"/>
  <meta name="description" content="<%= yield :title %> – Administrace"/>
  <title><%= yield :title %> | <%= t('admin.admin') %> </title>
  <%= stylesheet_link_tag "admin-core" %>
  <%= javascript_include_tag "admin-core" %>

  <% if defined? EtabliocmsPages %>
      <%= stylesheet_link_tag "admin-pages" %>
      <%= javascript_include_tag "admin-pages" %>
  <% end %>

  <% EtabliocmsCore.stylesheets.each do |stylesheet| %>
      <%= stylesheet_link_tag stylesheet %>
  <% end %>

  <% EtabliocmsCore.javascripts.each do |javascript| %>
      <%= javascript_include_tag javascript %>
  <% end %>

  <%= csrf_meta_tags %>
</head>

<body class="<%= body_class %>">
<header id="topbar">
  <div class="container">
    <nav id="user-information">

      <% if etabliocms_core_user_signed_in? -%>
          <strong><%= t('common.logged') %>: <%= link_to current_etabliocms_core_user.email, admin_path %></strong>
          <ul>
            <li><%= link_to I18n.t('admin.show_public', :domain => request.host), "/", :'data-popup' => true %></li>
            <li><%= link_to I18n.t('common.logout'), destroy_etabliocms_core_user_session_path, {:title => t('common.logout'), :method => :delete} %></li>
          </ul>
      <% end -%>

    </nav>
  </div>
</header>

<div class="container">
  <div id="main">
    <div id="content">

      <%= render "layouts/flashes" %>

      <%= yield %>

    </div>

    <nav id="sidebar">
      <div id="sidebar-inner">
        <div id="sidebar-inner-inner">

          <% EtabliocmsCore.modules.each do |m| %>
              <%= render :partial => "layouts/sidebar_#{m}" %>
          <% end %>

          <h3><%= image_tag asset_path("admin/sidebar-help.png"), :alt => t('help.help') %><%= t('help.help') %></h3>
          <ul>
            <li><%= link_to_unless_current I18n.t('help.textile'), admin_textile_help_path %></li>
          </ul>

        </div>
      </div>
    </nav>

  </div>
</div>


<script>
    $(function() {
        Shared.initFlashClose();
        Admin.initPopUp();
    })
</script>

<%= yield :javascript %>

</body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title><%= @title %></title>
  <!--general stylesheet-->
  <style type="text/css">
      p {
          padding: 0;
          margin: 0;
      }

      h2, h3, p, li {
          font-family: Georgia, Serif;
      }

      td {
          vertical-align: top;
      }

      ul, ol {
          margin: 0;
          padding: 0;
      }

    h3 a {color: #535353;}
  </style>
</head>
<body marginheight="0" topmargin="0" marginwidth="0" leftmargin="0" background=""
      style="margin: 0px; background-color: #ffffff;" bgcolor="#ffffff">
<table cellspacing="0" border="0" cellpadding="0" width="100%">
  <tbody>
  <tr valign="top">
    <td><!--container-->
      <table cellspacing="0" cellpadding="0" border="0" align="center" width="750" bgcolor="#ffffff">
        <tbody>
        <tr>
          <td valign="top" bgcolor="#ffffff" align="center">
            <table cellspacing="0" border="0" cellpadding="0" width="700">
              <tbody>
              <tr>
                <td valign="top" height="37" style="height: 37px;">&nbsp;</td>
              </tr>
              <tr>
                <td valign="top" colspan="2" style="text-align: left;">
                  <h1 style="margin: 0; padding: 0; font-size: 36px; color: #e6601a; font-weight: bold;font-family: 'Arial Black', Gadget, sans-serif;">
                    <a href="http://<%= configatron.host %>" style="color: #e6601a;text-decoration:none;font-family: 'Arial Black', Gadget, sans-serif;" title="<%= configatron.description %>">
                      <%= configatron.name %></a>
                  </h1>
                </td>
              </tr>
              <tr>
                <td valign="top" height="27" style="height: 15px;">&nbsp;</td>
              </tr>
              <tr>
                <td valign="top" width="100%">
                  <table cellspacing="0" border="0" cellpadding="0" width="100%">
                    <tr>
                      <td valign="top">
                        <%= yield %>
                      </td>
                    </tr>
                  </table>


                </td>
              </tr>
              <tr>
                <td valign="top" height="40" bgcolor="#ffffff" style="height: 40px;">&nbsp;</td>
              </tr>
              <tr>
                <td valign="middle" height="38"
                    style="height: 38px; vertical-align: middle; border-top-color: #d6d6d6; border-top-width: 1px; border-top-style: solid;">
                  <p style="font-size: 11px; font-weight: bold; color: #8a8a8a; text-align: center;">
                    Tým <strong><a href="http://<%= configatron.host %>" style="color:#e6601a;text-decoration:none"><%= configatron.name %></a></strong>
                    <a href="mailto:<%= configatron.email %>" style="color:#e6601a;text-decoration:none"><%= configatron.email %></a>
                  </p>
                </td>
              </tr>
              </tbody>
            </table>
          </td>
          <!--/content-->
        </tr>
        </tbody>
      </table>
      <!--/container-->
    </td>
  </tr>
  </tbody>
</table>
</body>
</html>